language: php
sudo: false

env:
  - DB_USERNAME=travis DB=mysql
  - DB_USERNAME=travis DB=mariadb
services:
  - mysql
addons:
  mariadb: '10.2'

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
before_install:
  - if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then mysql -e 'CREATE DATABASE flarum;'; fi
before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

notifications:
  email:
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)
