name: JavaScript

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Cache node_modules
        uses: actions/cache@v2
        id: module-cache
        with:
          path: ./js/node_modules
          key: ${{ runner.os }}-node-modules-${{ github.sha }}-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.sha }}-

      - uses: flarum/action-build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
